services:
  localsendy:
    image: ghcr.io/ca-x/localsendy:latest
    build:
      context: .
    container_name: localsendy
    restart: unless-stopped
    network_mode: host
    environment:
      LOCALSENDY_BIND: ${LOCALSENDY_BIND:-0.0.0.0:8080}
      LOCALSENDY_ALIAS_PREFIX: ${LOCALSENDY_ALIAS_PREFIX:-}
      LOCALSENDY_ALIAS_LOCALE: ${LOCALSENDY_ALIAS_LOCALE:-auto}
      LOCALSENDY_DEVICE_TYPE: ${LOCALSENDY_DEVICE_TYPE:-server}
      LOCALSENDY_DEVICE_MODEL: ${LOCALSENDY_DEVICE_MODEL:-Linux}
      LOCALSENDY_PORT: ${LOCALSENDY_PORT:-53317}
      LOCALSENDY_DATA_DIR: /data
      LOCALSENDY_DOWNLOAD_DIR: ${LOCALSENDY_DOWNLOAD_DIR:-/data/downloads}
      LOCALSENDY_TEMP_DIR: ${LOCALSENDY_TEMP_DIR:-/data/tmp}
      LOCALSENDY_AUTO_ACCEPT: ${LOCALSENDY_AUTO_ACCEPT:-false}
      LOCALSENDY_NETWORK_INTERFACES: ${LOCALSENDY_NETWORK_INTERFACES:-all}
      RUST_LOG: localsendy=info,tower_http=info
    volumes:
      - ./data:/data
